FROM golang:1.25-bookworm AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace

COPY . .

WORKDIR /workspace/bobravoz-grpc
RUN go mod download

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o connector cmd/connector/main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/bobravoz-grpc/connector /connector
USER 65532:65532

ENTRYPOINT ["/connector"]
