apiVersion: v1
kind: Service
metadata:
  name: bobravoz-grpc-hub
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: bobravoz-grpc
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    control-plane: controller-manager
