apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bobravoz.configName" . }}
  namespace: {{ include "bobravoz.effectiveConfigNamespace" . }}
  labels:
    {{- include "bobravoz.labels" . | nindent 4 }}
data:
  {{- $connectorTag := .Values.connectorImage.tag | default .Chart.AppVersion }}
  connector.image: {{ printf "%s:%s" .Values.connectorImage.repository $connectorTag | quote }}
  connector.image-pull-policy: {{ .Values.connectorImage.pullPolicy | quote }}
  {{- range $key, $value := .Values.operatorConfigData }}
  {{- if and (ne $key "connector.image") (ne $key "connector.image-pull-policy") }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
