{{- if .Values.leaderElection.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bobravoz.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "bobravoz.leaderElectionNamespace" . }}
  labels:
    {{- include "bobravoz.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bobravoz.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "bobravoz.serviceAccountName" . }}
    namespace: {{ include "bobravoz.namespace" . }}
{{- end }}
