// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: main.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Hub_Process_FullMethodName = "/proto.Hub/Process"
)

// HubClient is the client API for Hub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HubClient interface {
	// Process is a bidirectional streaming RPC that allows the hub to process and forward data between engrams.
	Process(ctx context.Context, opts ...grpc.CallOption) (Hub_ProcessClient, error)
}

type hubClient struct {
	cc grpc.ClientConnInterface
}

func NewHubClient(cc grpc.ClientConnInterface) HubClient {
	return &hubClient{cc}
}

func (c *hubClient) Process(ctx context.Context, opts ...grpc.CallOption) (Hub_ProcessClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Hub_ServiceDesc.Streams[0], Hub_Process_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &hubProcessClient{ClientStream: stream}
	return x, nil
}

type Hub_ProcessClient interface {
	Send(*DataPacket) error
	Recv() (*DataPacket, error)
	grpc.ClientStream
}

type hubProcessClient struct {
	grpc.ClientStream
}

func (x *hubProcessClient) Send(m *DataPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hubProcessClient) Recv() (*DataPacket, error) {
	m := new(DataPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HubServer is the server API for Hub service.
// All implementations must embed UnimplementedHubServer
// for forward compatibility
type HubServer interface {
	// Process is a bidirectional streaming RPC that allows the hub to process and forward data between engrams.
	Process(Hub_ProcessServer) error
	mustEmbedUnimplementedHubServer()
}

// UnimplementedHubServer must be embedded to have forward compatible implementations.
type UnimplementedHubServer struct {
}

func (UnimplementedHubServer) Process(Hub_ProcessServer) error {
	return status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedHubServer) mustEmbedUnimplementedHubServer() {}

// UnsafeHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubServer will
// result in compilation errors.
type UnsafeHubServer interface {
	mustEmbedUnimplementedHubServer()
}

func RegisterHubServer(s grpc.ServiceRegistrar, srv HubServer) {
	s.RegisterService(&Hub_ServiceDesc, srv)
}

func _Hub_Process_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HubServer).Process(&hubProcessServer{ServerStream: stream})
}

type Hub_ProcessServer interface {
	Send(*DataPacket) error
	Recv() (*DataPacket, error)
	grpc.ServerStream
}

type hubProcessServer struct {
	grpc.ServerStream
}

func (x *hubProcessServer) Send(m *DataPacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hubProcessServer) Recv() (*DataPacket, error) {
	m := new(DataPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Hub_ServiceDesc is the grpc.ServiceDesc for Hub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Hub",
	HandlerType: (*HubServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Process",
			Handler:       _Hub_Process_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "main.proto",
}
