apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: bobravoz-grpc
    app.kubernetes.io/managed-by: kustomize
  annotations:
    kustomize.config.k8s.io/skip-name-prefix: "true"
  name: hub-tls
  namespace: system
spec:
  secretName: bobravoz-grpc-hub-tls
  dnsNames:
    - HUB_SERVICE_NAME.HUB_SERVICE_NAMESPACE.svc
    - HUB_SERVICE_NAME.HUB_SERVICE_NAMESPACE.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: bobrapet-shared-ca
  privateKey:
    rotationPolicy: Always